<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Province;
use App\Models\City;

class LocationSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed 38 Provinces of Indonesia
        $provinces = [
            ['id' => 1, 'province' => 'DKI Jakarta'],
            ['id' => 2, 'province' => 'Jawa Barat'],
            ['id' => 3, 'province' => 'Jawa Tengah'],
            ['id' => 4, 'province' => 'Jawa Timur'],
            ['id' => 5, 'province' => 'Banten'],
            ['id' => 6, 'province' => 'DI Yogyakarta'],
            ['id' => 7, 'province' => 'Aceh'],
            ['id' => 8, 'province' => 'Sumatera Utara'],
            ['id' => 9, 'province' => 'Sumatera Barat'],
            ['id' => 10, 'province' => 'Riau'],
            ['id' => 11, 'province' => 'Kepulauan Riau'],
            ['id' => 12, 'province' => 'Jambi'],
            ['id' => 13, 'province' => 'Sumatera Selatan'],
            ['id' => 14, 'province' => 'Bangka Belitung'],
            ['id' => 15, 'province' => 'Bengkulu'],
            ['id' => 16, 'province' => 'Lampung'],
            ['id' => 17, 'province' => 'Bali'],
            ['id' => 18, 'province' => 'Nusa Tenggara Barat (NTB)'],
            ['id' => 19, 'province' => 'Nusa Tenggara Timur (NTT)'],
            ['id' => 20, 'province' => 'Kalimantan Barat'],
            ['id' => 21, 'province' => 'Kalimantan Tengah'],
            ['id' => 22, 'province' => 'Kalimantan Selatan'],
            ['id' => 23, 'province' => 'Kalimantan Timur'],
            ['id' => 24, 'province' => 'Kalimantan Utara'],
            ['id' => 25, 'province' => 'Sulawesi Utara'],
            ['id' => 26, 'province' => 'Sulawesi Tengah'],
            ['id' => 27, 'province' => 'Sulawesi Selatan'],
            ['id' => 28, 'province' => 'Sulawesi Tenggara'],
            ['id' => 29, 'province' => 'Gorontalo'],
            ['id' => 30, 'province' => 'Sulawesi Barat'],
            ['id' => 31, 'province' => 'Maluku'],
            ['id' => 32, 'province' => 'Maluku Utara'],
            ['id' => 33, 'province' => 'Papua'],
            ['id' => 34, 'province' => 'Papua Barat'],
            ['id' => 35, 'province' => 'Papua Selatan'],
            ['id' => 36, 'province' => 'Papua Tengah'],
            ['id' => 37, 'province' => 'Papua Pegunungan'],
            ['id' => 38, 'province' => 'Papua Barat Daya'],
        ];

        foreach ($provinces as $prov) {
            Province::firstOrCreate(['id' => $prov['id']], ['province' => $prov['province']]);
        }

        // 2. Seed Cities & Regencies for all 38 Provinces
        $cities = [
            // 1. DKI Jakarta
            ['province_id' => 1, 'city' => 'Jakarta Selatan'],
            ['province_id' => 1, 'city' => 'Jakarta Pusat'],
            ['province_id' => 1, 'city' => 'Jakarta Barat'],
            ['province_id' => 1, 'city' => 'Jakarta Utara'],
            ['province_id' => 1, 'city' => 'Jakarta Timur'],
            ['province_id' => 1, 'city' => 'Kepulauan Seribu'],

            // 2. Jawa Barat
            ['province_id' => 2, 'city' => 'Bandung'],
            ['province_id' => 2, 'city' => 'Bekasi'],
            ['province_id' => 2, 'city' => 'Depok'],
            ['province_id' => 2, 'city' => 'Bogor'],
            ['province_id' => 2, 'city' => 'Cimahi'],
            ['province_id' => 2, 'city' => 'Cirebon'],
            ['province_id' => 2, 'city' => 'Sukabumi'],
            ['province_id' => 2, 'city' => 'Tasikmalaya'],
            ['province_id' => 2, 'city' => 'Banjar'],
            ['province_id' => 2, 'city' => 'Garut'],
            ['province_id' => 2, 'city' => 'Sumedang'],
            ['province_id' => 2, 'city' => 'Karawang'],
            ['province_id' => 2, 'city' => 'Purwakarta'],
            ['province_id' => 2, 'city' => 'Subang'],
            ['province_id' => 2, 'city' => 'Indramayu'],
            ['province_id' => 2, 'city' => 'Majalengka'],
            ['province_id' => 2, 'city' => 'Ciamis'],
            ['province_id' => 2, 'city' => 'Kuningan'],
            ['province_id' => 2, 'city' => 'Cianjur'],
            ['province_id' => 2, 'city' => 'Kab. Bandung'],
            ['province_id' => 2, 'city' => 'Kab. Bandung Barat'],
            ['province_id' => 2, 'city' => 'Kab. Bogor'],
            ['province_id' => 2, 'city' => 'Kab. Bekasi'],
            ['province_id' => 2, 'city' => 'Kab. Sukabumi'],
            ['province_id' => 2, 'city' => 'Kab. Cirebon'],
            ['province_id' => 2, 'city' => 'Kab. Tasikmalaya'],

            // 3. Jawa Tengah
            ['province_id' => 3, 'city' => 'Semarang'],
            ['province_id' => 3, 'city' => 'Surakarta (Solo)'],
            ['province_id' => 3, 'city' => 'Magelang'],
            ['province_id' => 3, 'city' => 'Salatiga'],
            ['province_id' => 3, 'city' => 'Pekalongan'],
            ['province_id' => 3, 'city' => 'Tegal'],
            ['province_id' => 3, 'city' => 'Kudus'],
            ['province_id' => 3, 'city' => 'Jepara'],
            ['province_id' => 3, 'city' => 'Banyumas (Purwokerto)'],
            ['province_id' => 3, 'city' => 'Cilacap'],
            ['province_id' => 3, 'city' => 'Sragen'],
            ['province_id' => 3, 'city' => 'Karanganyar'],
            ['province_id' => 3, 'city' => 'Klaten'],
            ['province_id' => 3, 'city' => 'Boyolali'],
            ['province_id' => 3, 'city' => 'Sukoharjo'],
            ['province_id' => 3, 'city' => 'Pati'],
            ['province_id' => 3, 'city' => 'Wonogiri'],
            ['province_id' => 3, 'city' => 'Demak'],
            ['province_id' => 3, 'city' => 'Grobogan'],
            ['province_id' => 3, 'city' => 'Blora'],
            ['province_id' => 3, 'city' => 'Rembang'],
            ['province_id' => 3, 'city' => 'Temanggung'],
            ['province_id' => 3, 'city' => 'Kendal'],
            ['province_id' => 3, 'city' => 'Batang'],
            ['province_id' => 3, 'city' => 'Pemalang'],
            ['province_id' => 3, 'city' => 'Brebes'],
            ['province_id' => 3, 'city' => 'Purbalingga'],
            ['province_id' => 3, 'city' => 'Banjarnegara'],
            ['province_id' => 3, 'city' => 'Kebumen'],
            ['province_id' => 3, 'city' => 'Purworejo'],
            ['province_id' => 3, 'city' => 'Wonosobo'],

            // 4. Jawa Timur
            ['province_id' => 4, 'city' => 'Surabaya'],
            ['province_id' => 4, 'city' => 'Malang'],
            ['province_id' => 4, 'city' => 'Sidoarjo'],
            ['province_id' => 4, 'city' => 'Kediri'],
            ['province_id' => 4, 'city' => 'Madiun'],
            ['province_id' => 4, 'city' => 'Probolinggo'],
            ['province_id' => 4, 'city' => 'Pasuruan'],
            ['province_id' => 4, 'city' => 'Blitar'],
            ['province_id' => 4, 'city' => 'Batu'],
            ['province_id' => 4, 'city' => 'Gresik'],
            ['province_id' => 4, 'city' => 'Mojokerto'],
            ['province_id' => 4, 'city' => 'Jember'],
            ['province_id' => 4, 'city' => 'Banyuwangi'],
            ['province_id' => 4, 'city' => 'Bojonegoro'],
            ['province_id' => 4, 'city' => 'Tuban'],
            ['province_id' => 4, 'city' => 'Lamongan'],
            ['province_id' => 4, 'city' => 'Ponorogo'],
            ['province_id' => 4, 'city' => 'Tulungagung'],
            ['province_id' => 4, 'city' => 'Nganjuk'],
            ['province_id' => 4, 'city' => 'Jombang'],
            ['province_id' => 4, 'city' => 'Lumajang'],
            ['province_id' => 4, 'city' => 'Bondowoso'],
            ['province_id' => 4, 'city' => 'Situbondo'],
            ['province_id' => 4, 'city' => 'Sampang'],
            ['province_id' => 4, 'city' => 'Pamekasan'],
            ['province_id' => 4, 'city' => 'Sumenep'],
            ['province_id' => 4, 'city' => 'Bangkalan'],
            ['province_id' => 4, 'city' => 'Kab. Malang'],
            ['province_id' => 4, 'city' => 'Kab. Kediri'],
            ['province_id' => 4, 'city' => 'Kab. Pasuruan'],

            // 5. Banten
            ['province_id' => 5, 'city' => 'Tangerang'],
            ['province_id' => 5, 'city' => 'Tangerang Selatan'],
            ['province_id' => 5, 'city' => 'Serang'],
            ['province_id' => 5, 'city' => 'Cilegon'],
            ['province_id' => 5, 'city' => 'Lebak'],
            ['province_id' => 5, 'city' => 'Pandeglang'],
            ['province_id' => 5, 'city' => 'Kab. Tangerang'],
            ['province_id' => 5, 'city' => 'Kab. Serang'],

            // 6. DI Yogyakarta
            ['province_id' => 6, 'city' => 'Yogyakarta'],
            ['province_id' => 6, 'city' => 'Sleman'],
            ['province_id' => 6, 'city' => 'Bantul'],
            ['province_id' => 6, 'city' => 'Gunungkidul'],
            ['province_id' => 6, 'city' => 'Kulon Progo'],

            // 7. Aceh
            ['province_id' => 7, 'city' => 'Banda Aceh'],
            ['province_id' => 7, 'city' => 'Sabang'],
            ['province_id' => 7, 'city' => 'Lhokseumawe'],
            ['province_id' => 7, 'city' => 'Langsa'],
            ['province_id' => 7, 'city' => 'Subulussalam'],
            ['province_id' => 7, 'city' => 'Aceh Besar'],
            ['province_id' => 7, 'city' => 'Aceh Barat'],
            ['province_id' => 7, 'city' => 'Aceh Selatan'],
            ['province_id' => 7, 'city' => 'Aceh Timur'],
            ['province_id' => 7, 'city' => 'Aceh Utara'],
            ['province_id' => 7, 'city' => 'Aceh Tengah'],
            ['province_id' => 7, 'city' => 'Aceh Tenggara'],
            ['province_id' => 7, 'city' => 'Aceh Singkil'],
            ['province_id' => 7, 'city' => 'Bireuen'],
            ['province_id' => 7, 'city' => 'Pidie'],
            ['province_id' => 7, 'city' => 'Pidie Jaya'],
            ['province_id' => 7, 'city' => 'Nagan Raya'],
            ['province_id' => 7, 'city' => 'Aceh Jaya'],
            ['province_id' => 7, 'city' => 'Aceh Barat Daya'],
            ['province_id' => 7, 'city' => 'Gayo Lues'],

            // 8. Sumatera Utara
            ['province_id' => 8, 'city' => 'Medan'],
            ['province_id' => 8, 'city' => 'Pematangsiantar'],
            ['province_id' => 8, 'city' => 'Sibolga'],
            ['province_id' => 8, 'city' => 'Tanjungbalai'],
            ['province_id' => 8, 'city' => 'Tebing Tinggi'],
            ['province_id' => 8, 'city' => 'Binjai'],
            ['province_id' => 8, 'city' => 'Padangsidimpuan'],
            ['province_id' => 8, 'city' => 'Gunungsitoli'],
            ['province_id' => 8, 'city' => 'Deli Serdang'],
            ['province_id' => 8, 'city' => 'Karo'],
            ['province_id' => 8, 'city' => 'Simalungun'],
            ['province_id' => 8, 'city' => 'Asahan'],
            ['province_id' => 8, 'city' => 'Labuhanbatu'],
            ['province_id' => 8, 'city' => 'Tapanuli Utara'],
            ['province_id' => 8, 'city' => 'Tapanuli Selatan'],
            ['province_id' => 8, 'city' => 'Tapanuli Tengah'],
            ['province_id' => 8, 'city' => 'Nias'],
            ['province_id' => 8, 'city' => 'Langkat'],
            ['province_id' => 8, 'city' => 'Serdang Bedagai'],
            ['province_id' => 8, 'city' => 'Humbang Hasundutan'],
            ['province_id' => 8, 'city' => 'Samosir'],

            // 9. Sumatera Barat
            ['province_id' => 9, 'city' => 'Padang'],
            ['province_id' => 9, 'city' => 'Bukittinggi'],
            ['province_id' => 9, 'city' => 'Payakumbuh'],
            ['province_id' => 9, 'city' => 'Pariaman'],
            ['province_id' => 9, 'city' => 'Solok'],
            ['province_id' => 9, 'city' => 'Sawahlunto'],
            ['province_id' => 9, 'city' => 'Padang Panjang'],
            ['province_id' => 9, 'city' => 'Agam'],
            ['province_id' => 9, 'city' => 'Pasaman'],
            ['province_id' => 9, 'city' => 'Pasaman Barat'],
            ['province_id' => 9, 'city' => 'Tanah Datar'],
            ['province_id' => 9, 'city' => 'Pesisir Selatan'],
            ['province_id' => 9, 'city' => 'Lima Puluh Kota'],
            ['province_id' => 9, 'city' => 'Sijunjung'],
            ['province_id' => 9, 'city' => 'Dharmasraya'],
            ['province_id' => 9, 'city' => 'Solok Selatan'],

            // 10. Riau
            ['province_id' => 10, 'city' => 'Pekanbaru'],
            ['province_id' => 10, 'city' => 'Dumai'],
            ['province_id' => 10, 'city' => 'Bengkalis'],
            ['province_id' => 10, 'city' => 'Kampar'],
            ['province_id' => 10, 'city' => 'Indragiri Hulu'],
            ['province_id' => 10, 'city' => 'Indragiri Hilir'],
            ['province_id' => 10, 'city' => 'Siak'],
            ['province_id' => 10, 'city' => 'Rokan Hulu'],
            ['province_id' => 10, 'city' => 'Rokan Hilir'],
            ['province_id' => 10, 'city' => 'Pelalawan'],
            ['province_id' => 10, 'city' => 'Kuantan Singingi'],
            ['province_id' => 10, 'city' => 'Kepulauan Meranti'],

            // 11. Kepulauan Riau
            ['province_id' => 11, 'city' => 'Batam'],
            ['province_id' => 11, 'city' => 'Tanjungpinang'],
            ['province_id' => 11, 'city' => 'Bintan'],
            ['province_id' => 11, 'city' => 'Karimun'],
            ['province_id' => 11, 'city' => 'Natuna'],
            ['province_id' => 11, 'city' => 'Anambas'],
            ['province_id' => 11, 'city' => 'Lingga'],

            // 12. Jambi
            ['province_id' => 12, 'city' => 'Jambi'],
            ['province_id' => 12, 'city' => 'Sungai Penuh'],
            ['province_id' => 12, 'city' => 'Muaro Jambi'],
            ['province_id' => 12, 'city' => 'Bungo'],
            ['province_id' => 12, 'city' => 'Tebo'],
            ['province_id' => 12, 'city' => 'Batanghari'],
            ['province_id' => 12, 'city' => 'Kerinci'],
            ['province_id' => 12, 'city' => 'Merangin'],
            ['province_id' => 12, 'city' => 'Sarolangun'],
            ['province_id' => 12, 'city' => 'Tanjung Jabung Barat'],
            ['province_id' => 12, 'city' => 'Tanjung Jabung Timur'],

            // 13. Sumatera Selatan
            ['province_id' => 13, 'city' => 'Palembang'],
            ['province_id' => 13, 'city' => 'Prabumulih'],
            ['province_id' => 13, 'city' => 'Lubuklinggau'],
            ['province_id' => 13, 'city' => 'Pagar Alam'],
            ['province_id' => 13, 'city' => 'Ogan Komering Ilir'],
            ['province_id' => 13, 'city' => 'Ogan Ilir'],
            ['province_id' => 13, 'city' => 'Banyuasin'],
            ['province_id' => 13, 'city' => 'Muara Enim'],
            ['province_id' => 13, 'city' => 'Musi Banyuasin'],
            ['province_id' => 13, 'city' => 'Lahat'],
            ['province_id' => 13, 'city' => 'Ogan Komering Ulu'],
            ['province_id' => 13, 'city' => 'OKU Timur'],
            ['province_id' => 13, 'city' => 'OKU Selatan'],
            ['province_id' => 13, 'city' => 'Musi Rawas'],

            // 14. Bangka Belitung
            ['province_id' => 14, 'city' => 'Pangkalpinang'],
            ['province_id' => 14, 'city' => 'Belitung'],
            ['province_id' => 14, 'city' => 'Belitung Timur'],
            ['province_id' => 14, 'city' => 'Bangka'],
            ['province_id' => 14, 'city' => 'Bangka Barat'],
            ['province_id' => 14, 'city' => 'Bangka Selatan'],
            ['province_id' => 14, 'city' => 'Bangka Tengah'],

            // 15. Bengkulu
            ['province_id' => 15, 'city' => 'Bengkulu'],
            ['province_id' => 15, 'city' => 'Rejang Lebong'],
            ['province_id' => 15, 'city' => 'Bengkulu Utara'],
            ['province_id' => 15, 'city' => 'Bengkulu Selatan'],
            ['province_id' => 15, 'city' => 'Mukomuko'],
            ['province_id' => 15, 'city' => 'Seluma'],
            ['province_id' => 15, 'city' => 'Kaur'],
            ['province_id' => 15, 'city' => 'Kepahiang'],
            ['province_id' => 15, 'city' => 'Lebong'],
            ['province_id' => 15, 'city' => 'Bengkulu Tengah'],

            // 16. Lampung
            ['province_id' => 16, 'city' => 'Bandar Lampung'],
            ['province_id' => 16, 'city' => 'Metro'],
            ['province_id' => 16, 'city' => 'Lampung Selatan'],
            ['province_id' => 16, 'city' => 'Lampung Tengah'],
            ['province_id' => 16, 'city' => 'Lampung Utara'],
            ['province_id' => 16, 'city' => 'Lampung Barat'],
            ['province_id' => 16, 'city' => 'Tanggamus'],
            ['province_id' => 16, 'city' => 'Pringsewu'],
            ['province_id' => 16, 'city' => 'Pesawaran'],
            ['province_id' => 16, 'city' => 'Tulang Bawang'],
            ['province_id' => 16, 'city' => 'Lampung Timur'],
            ['province_id' => 16, 'city' => 'Way Kanan'],
            ['province_id' => 16, 'city' => 'Mesuji'],

            // 17. Bali
            ['province_id' => 17, 'city' => 'Denpasar'],
            ['province_id' => 17, 'city' => 'Badung'],
            ['province_id' => 17, 'city' => 'Gianyar'],
            ['province_id' => 17, 'city' => 'Tabanan'],
            ['province_id' => 17, 'city' => 'Buleleng'],
            ['province_id' => 17, 'city' => 'Klungkung'],
            ['province_id' => 17, 'city' => 'Bangli'],
            ['province_id' => 17, 'city' => 'Karangasem'],
            ['province_id' => 17, 'city' => 'Jembrana'],

            // 18. Nusa Tenggara Barat (NTB)
            ['province_id' => 18, 'city' => 'Mataram'],
            ['province_id' => 18, 'city' => 'Bima'],
            ['province_id' => 18, 'city' => 'Lombok Barat'],
            ['province_id' => 18, 'city' => 'Lombok Tengah'],
            ['province_id' => 18, 'city' => 'Lombok Timur'],
            ['province_id' => 18, 'city' => 'Lombok Utara'],
            ['province_id' => 18, 'city' => 'Sumbawa'],
            ['province_id' => 18, 'city' => 'Sumbawa Barat'],
            ['province_id' => 18, 'city' => 'Dompu'],

            // 19. Nusa Tenggara Timur (NTT)
            ['province_id' => 19, 'city' => 'Kupang'],
            ['province_id' => 19, 'city' => 'Manggarai Barat (Labuan Bajo)'],
            ['province_id' => 19, 'city' => 'Ende'],
            ['province_id' => 19, 'city' => 'Sikka'],
            ['province_id' => 19, 'city' => 'Sumba Timur'],
            ['province_id' => 19, 'city' => 'Sumba Barat'],
            ['province_id' => 19, 'city' => 'Belu'],
            ['province_id' => 19, 'city' => 'Timor Tengah Selatan'],
            ['province_id' => 19, 'city' => 'Timor Tengah Utara'],
            ['province_id' => 19, 'city' => 'Alor'],
            ['province_id' => 19, 'city' => 'Rote Ndao'],
            ['province_id' => 19, 'city' => 'Flores Timur'],

            // 20. Kalimantan Barat
            ['province_id' => 20, 'city' => 'Pontianak'],
            ['province_id' => 20, 'city' => 'Singkawang'],
            ['province_id' => 20, 'city' => 'Kubu Raya'],
            ['province_id' => 20, 'city' => 'Sambas'],
            ['province_id' => 20, 'city' => 'Ketapang'],
            ['province_id' => 20, 'city' => 'Sintang'],
            ['province_id' => 20, 'city' => 'Sanggau'],
            ['province_id' => 20, 'city' => 'Landak'],
            ['province_id' => 20, 'city' => 'Mempawah'],
            ['province_id' => 20, 'city' => 'Bengkayang'],
            ['province_id' => 20, 'city' => 'Kapuas Hulu'],

            // 21. Kalimantan Tengah
            ['province_id' => 21, 'city' => 'Palangkaraya'],
            ['province_id' => 21, 'city' => 'Kotawaringin Barat'],
            ['province_id' => 21, 'city' => 'Kotawaringin Timur'],
            ['province_id' => 21, 'city' => 'Kapuas'],
            ['province_id' => 21, 'city' => 'Barito Selatan'],
            ['province_id' => 21, 'city' => 'Barito Utara'],
            ['province_id' => 21, 'city' => 'Murung Raya'],
            ['province_id' => 21, 'city' => 'Katingan'],
            ['province_id' => 21, 'city' => 'Seruyan'],

            // 22. Kalimantan Selatan
            ['province_id' => 22, 'city' => 'Banjarmasin'],
            ['province_id' => 22, 'city' => 'Banjarbaru'],
            ['province_id' => 22, 'city' => 'Martapura (Kab. Banjar)'],
            ['province_id' => 22, 'city' => 'Tanah Laut'],
            ['province_id' => 22, 'city' => 'Kotabaru'],
            ['province_id' => 22, 'city' => 'Tabalong'],
            ['province_id' => 22, 'city' => 'Tanah Bumbu'],
            ['province_id' => 22, 'city' => 'Barito Kuala'],
            ['province_id' => 22, 'city' => 'Tapin'],
            ['province_id' => 22, 'city' => 'Hulu Sungai Selatan'],
            ['province_id' => 22, 'city' => 'Hulu Sungai Tengah'],
            ['province_id' => 22, 'city' => 'Hulu Sungai Utara'],

            // 23. Kalimantan Timur
            ['province_id' => 23, 'city' => 'Samarinda'],
            ['province_id' => 23, 'city' => 'Balikpapan'],
            ['province_id' => 23, 'city' => 'Bontang'],
            ['province_id' => 23, 'city' => 'Kutai Kartanegara'],
            ['province_id' => 23, 'city' => 'Kutai Timur'],
            ['province_id' => 23, 'city' => 'Paser'],
            ['province_id' => 23, 'city' => 'Berau'],
            ['province_id' => 23, 'city' => 'Kutai Barat'],
            ['province_id' => 23, 'city' => 'Penajam Paser Utara'],

            // 24. Kalimantan Utara
            ['province_id' => 24, 'city' => 'Tarakan'],
            ['province_id' => 24, 'city' => 'Tanjung Selor (Bulungan)'],
            ['province_id' => 24, 'city' => 'Nunukan'],
            ['province_id' => 24, 'city' => 'Malinau'],
            ['province_id' => 24, 'city' => 'Tana Tidung'],

            // 25. Sulawesi Utara
            ['province_id' => 25, 'city' => 'Manado'],
            ['province_id' => 25, 'city' => 'Bitung'],
            ['province_id' => 25, 'city' => 'Tomohon'],
            ['province_id' => 25, 'city' => 'Kotamobagu'],
            ['province_id' => 25, 'city' => 'Minahasa'],
            ['province_id' => 25, 'city' => 'Minahasa Utara'],
            ['province_id' => 25, 'city' => 'Minahasa Selatan'],
            ['province_id' => 25, 'city' => 'Minahasa Tenggara'],
            ['province_id' => 25, 'city' => 'Kepulauan Sangihe'],
            ['province_id' => 25, 'city' => 'Kepulauan Talaud'],

            // 26. Sulawesi Tengah
            ['province_id' => 26, 'city' => 'Palu'],
            ['province_id' => 26, 'city' => 'Luwuk (Banggai)'],
            ['province_id' => 26, 'city' => 'Poso'],
            ['province_id' => 26, 'city' => 'Donggala'],
            ['province_id' => 26, 'city' => 'Tolitoli'],
            ['province_id' => 26, 'city' => 'Morowali'],
            ['province_id' => 26, 'city' => 'Morowali Utara'],
            ['province_id' => 26, 'city' => 'Parigi Moutong'],
            ['province_id' => 26, 'city' => 'Buol'],
            ['province_id' => 26, 'city' => 'Sigi'],

            // 27. Sulawesi Selatan
            ['province_id' => 27, 'city' => 'Makassar'],
            ['province_id' => 27, 'city' => 'Palopo'],
            ['province_id' => 27, 'city' => 'Parepare'],
            ['province_id' => 27, 'city' => 'Bone'],
            ['province_id' => 27, 'city' => 'Gowa'],
            ['province_id' => 27, 'city' => 'Maros'],
            ['province_id' => 27, 'city' => 'Bulukumba'],
            ['province_id' => 27, 'city' => 'Bantaeng'],
            ['province_id' => 27, 'city' => 'Toraja Utara'],
            ['province_id' => 27, 'city' => 'Tana Toraja'],
            ['province_id' => 27, 'city' => 'Luwu Utara'],
            ['province_id' => 27, 'city' => 'Luwu Timur'],
            ['province_id' => 27, 'city' => 'Sinjai'],
            ['province_id' => 27, 'city' => 'Pangkajene dan Kepulauan'],
            ['province_id' => 27, 'city' => 'Barru'],
            ['province_id' => 27, 'city' => 'Soppeng'],
            ['province_id' => 27, 'city' => 'Wajo'],
            ['province_id' => 27, 'city' => 'Sidrap'],
            ['province_id' => 27, 'city' => 'Pinrang'],
            ['province_id' => 27, 'city' => 'Jeneponto'],
            ['province_id' => 27, 'city' => 'Takalar'],

            // 28. Sulawesi Tenggara
            ['province_id' => 28, 'city' => 'Kendari'],
            ['province_id' => 28, 'city' => 'Baubau'],
            ['province_id' => 28, 'city' => 'Kolaka'],
            ['province_id' => 28, 'city' => 'Konawe'],
            ['province_id' => 28, 'city' => 'Muna'],
            ['province_id' => 28, 'city' => 'Buton'],
            ['province_id' => 28, 'city' => 'Bombana'],
            ['province_id' => 28, 'city' => 'Wakatobi'],
            ['province_id' => 28, 'city' => 'Kolaka Utara'],

            // 29. Gorontalo
            ['province_id' => 29, 'city' => 'Gorontalo'],
            ['province_id' => 29, 'city' => 'Limboto (Kab. Gorontalo)'],
            ['province_id' => 29, 'city' => 'Bone Bolango'],
            ['province_id' => 29, 'city' => 'Pohuwato'],
            ['province_id' => 29, 'city' => 'Boalemo'],
            ['province_id' => 29, 'city' => 'Gorontalo Utara'],

            // 30. Sulawesi Barat
            ['province_id' => 30, 'city' => 'Mamuju'],
            ['province_id' => 30, 'city' => 'Polewali Mandar'],
            ['province_id' => 30, 'city' => 'Majene'],
            ['province_id' => 30, 'city' => 'Mamasa'],
            ['province_id' => 30, 'city' => 'Pasangkayu'],
            ['province_id' => 30, 'city' => 'Mamuju Tengah'],

            // 31. Maluku
            ['province_id' => 31, 'city' => 'Ambon'],
            ['province_id' => 31, 'city' => 'Tual'],
            ['province_id' => 31, 'city' => 'Maluku Tengah'],
            ['province_id' => 31, 'city' => 'Seram Bagian Barat'],
            ['province_id' => 31, 'city' => 'Seram Bagian Timur'],
            ['province_id' => 31, 'city' => 'Maluku Tenggara'],
            ['province_id' => 31, 'city' => 'Buru'],
            ['province_id' => 31, 'city' => 'Buru Selatan'],
            ['province_id' => 31, 'city' => 'Kepulauan Aru'],
            ['province_id' => 31, 'city' => 'Kepulauan Tanimbar'],

            // 32. Maluku Utara
            ['province_id' => 32, 'city' => 'Ternate'],
            ['province_id' => 32, 'city' => 'Tidore Kepulauan'],
            ['province_id' => 32, 'city' => 'Halmahera Utara'],
            ['province_id' => 32, 'city' => 'Halmahera Selatan'],
            ['province_id' => 32, 'city' => 'Halmahera Barat'],
            ['province_id' => 32, 'city' => 'Halmahera Timur'],
            ['province_id' => 32, 'city' => 'Halmahera Tengah'],
            ['province_id' => 32, 'city' => 'Kepulauan Sula'],
            ['province_id' => 32, 'city' => 'Pulau Morotai'],

            // 33. Papua
            ['province_id' => 33, 'city' => 'Jayapura'],
            ['province_id' => 33, 'city' => 'Kab. Jayapura'],
            ['province_id' => 33, 'city' => 'Keerom'],
            ['province_id' => 33, 'city' => 'Biak Numfor'],
            ['province_id' => 33, 'city' => 'Kepulauan Yapen'],
            ['province_id' => 33, 'city' => 'Sarmi'],
            ['province_id' => 33, 'city' => 'Waropen'],
            ['province_id' => 33, 'city' => 'Supiori'],

            // 34. Papua Barat
            ['province_id' => 34, 'city' => 'Manokwari'],
            ['province_id' => 34, 'city' => 'Teluk Bintuni'],
            ['province_id' => 34, 'city' => 'Fakfak'],
            ['province_id' => 34, 'city' => 'Kaimana'],
            ['province_id' => 34, 'city' => 'Teluk Wondama'],
            ['province_id' => 34, 'city' => 'Pegunungan Arfak'],

            // 35. Papua Selatan
            ['province_id' => 35, 'city' => 'Merauke'],
            ['province_id' => 35, 'city' => 'Boven Digoel'],
            ['province_id' => 35, 'city' => 'Mappi'],
            ['province_id' => 35, 'city' => 'Asmat'],

            // 36. Papua Tengah
            ['province_id' => 36, 'city' => 'Nabire'],
            ['province_id' => 36, 'city' => 'Mimika (Timika)'],
            ['province_id' => 36, 'city' => 'Paniai'],
            ['province_id' => 36, 'city' => 'Puncak Jaya'],
            ['province_id' => 36, 'city' => 'Puncak'],
            ['province_id' => 36, 'city' => 'Intan Jaya'],
            ['province_id' => 36, 'city' => 'Dogiyai'],
            ['province_id' => 36, 'city' => 'Deiyai'],

            // 37. Papua Pegunungan
            ['province_id' => 37, 'city' => 'Jayawijaya (Wamena)'],
            ['province_id' => 37, 'city' => 'Lanny Jaya'],
            ['province_id' => 37, 'city' => 'Nduga'],
            ['province_id' => 37, 'city' => 'Yahukimo'],
            ['province_id' => 37, 'city' => 'Yalimo'],
            ['province_id' => 37, 'city' => 'Pegunungan Bintang'],
            ['province_id' => 37, 'city' => 'Tolikara'],

            // 38. Papua Barat Daya
            ['province_id' => 38, 'city' => 'Sorong'],
            ['province_id' => 38, 'city' => 'Kab. Sorong'],
            ['province_id' => 38, 'city' => 'Raja Ampat'],
            ['province_id' => 38, 'city' => 'Tambrauw'],
            ['province_id' => 38, 'city' => 'Maybrat'],
            ['province_id' => 38, 'city' => 'Sorong Selatan'],
        ];

        foreach ($cities as $city) {
            City::firstOrCreate(
                ['province_id' => $city['province_id'], 'city' => $city['city']]
            );
        }
    }
}
